FROM linuxbrew/linuxbrew
ARG IMG_USR=bob

WORKDIR /home/${IMG_USR}/code/dotfiles
COPY . .
RUN ./install_pkg.sh
RUN useradd -m ${IMG_USR} -s /bin/zsh \
  && chown -R ${IMG_USR}: /home/${IMG_USR}
USER ${IMG_USR}
RUN ./link_files.sh
WORKDIR /home/${IMG_USR}
ENTRYPOINT ["zsh"]
