OPENAI_API_KEY: ENC[AES256_GCM,data:yEOeT0BdsLPNpebGtskCiu1Wrjomb5tDM8oo30FB2/OQSgQFNS8krUHNBoO2KTMRWL1JCOGoa9Q3xKknl/TMtMNAtw90arwLd8blgXlCCWAveOSnXd9Lpy7D2xdOUNOLfVr+JvCl/sprv1nJjJapw9yojMGRoIZ6mAShDayYPgXQV46jgMsv1OWONTJw87hFCQ5315VoW9FaQt7QVScfyyUMXzU=,iv:AbdV16ZxBHZ1/Q9liva+EyeIwa3ht4EOJB/OsjiigDg=,tag:OB31LEuuJGJdqLPyJ3j5wQ==,type:str]
GROQ_API_KEY: ENC[AES256_GCM,data:a32cegUSOAsu3dcF7iW4xEu/AhskkGHPYuDk+MBy3RMrzWMe3U3X6Iiwm4/rhfsYkOozULc5uAQ=,iv:AREHDYG/C7/PevbWnX/MSUdqN23Tq6X1jjr69pVB/6M=,tag:auFIgOTkAmX0g1PYYDEeGw==,type:str]
TAVILY_API_KEY: ENC[AES256_GCM,data:aoSncMCtC0I2mfEAlldJgDAiI9IWTBhxqrbM6eXEupu5OI8/T0Cd8r3E21kX4wguVKvHMT+f03IU,iv:Zpy5ZWH+vNSr9ETjrh2W7dhJmC9ojsmzu5OictstkGY=,tag:atNT9rXri+lvkqTXwQqiEQ==,type:str]
GH_TOKEN: ENC[AES256_GCM,data:zB59QUCleWnAFXVnBSrYr4D3pkLuTdf7cC/DSHWEdp6ygN7yhCdp1w==,iv:/x+N7ifG6x34Hp/NNtp5sf6SMNftT+6LM4u5J7uKe/k=,tag:TMwni2A2OE71+0dCO2SaAg==,type:str]
sops:
    age:
        - recipient: age13ftq7mduxhwc8pdez5p40wssl5hx95t4yytchcmy2spaynur8a6shxxmps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT0ppTjl6VSsxU0JORTYw
            Unc2MDR1YmJ1bVNnOWdrbEFMMU5TVDA3MVVzCnk2T3I2M3NmQ2x6RkozQldKbmVw
            ZDc0eTFnZkhZSHhZV3U1eDJLZEQ2WkkKLS0tIGtkRnhOcmJ5VFUxUTJZZ1B5Vmdp
            dytqb0ZIRitzVndkYkx6T3F5VFJTQXMKFZgc0OWMwMcmsaMy8Avf2qoUR6LptYLd
            kyfB7B8w/JEsabivQWTqBACuq3XThXw7q6sTYR8nGoSQFCPFQnkyBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T17:22:12Z"
    mac: ENC[AES256_GCM,data:WWZtKbexmIRMmzpW+mxL+spCfmkD59SR8benpeYtk5jdwTqtIa7SJCeT/GHRWYE6ExDh55gQuOEtEn7beIpztqU0BwAkXoRd8W8lbgB5bvoFqbz5FjhNcQDGPcwUlf6Wl3DI4hdRdRzmZc7CHGX/HS5x3+YHqZyvIZGbb4M7mjw=,iv:iB0DHNAw+5Fewv4SoDQfVrqV2esGpxyD8yD7v2g748c=,tag:Q3ugTPxz96Zi1r1YidesoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
