return {
  servers = {
    'bashls',
    -- 'clangd',
    -- 'cssls',
    'gopls',
    'basedpyright',
    'dockerls',
    'docker_compose_language_service',
    'helm_ls',
    'biome',
    -- 'html',
    'jsonls',
    -- 'neocmake',
    'ruff',
    -- 'rust_analyzer',
    'sqruff',
    -- 'stylelint-language-server',
    'terraformls',
    'tflint',
    'tsgo',
    -- 'vtsls',
    'lua_ls',
    'yamlls',
    'taplo',
    'ty',
  },

  -- list will be merged with the language servers listed above
  tools = {
    -- 'bash-debug-adapter',
    'biome',
    -- 'cmakelang',
    -- 'cmakelint',
    -- 'codelldb',
    'debugpy',
    'delve',
    'firefox-debug-adapter',
    'gofumpt',
    'goimports',
    'hadolint',
    'js-debug-adapter',
    'markdownlint',
    'markdown-toc',
    'prettier',
    'shellcheck',
    'shfmt',
    'stylua',
  },
}
