return {
  servers = {
    'bashls',
    -- 'clangd',
    -- 'cssls',
    'gopls',
    'dockerls',
    'docker_compose_language_service',
    'helm_ls',
    'biome',
    -- 'html',
    'jsonls', -- still complements biome
    -- 'neocmake',
    'ruff',
    -- 'rust_analyzer',
    'sqruff',
    -- 'stylelint-language-server',
    'terraformls',
    'tflint',
    'tsgo',
    'lua_ls',
    'yamlls',
    'taplo',
    'ty',
  },

  -- list will be merged with the language servers listed above
  tools = {
    -- 'bash-debug-adapter', -- mildly useful
    -- 'cmakelang',
    -- 'cmakelint',
    -- 'codelldb',
    -- 'debugpy', -- usually installed within the project
    'delve',
    -- 'firefox-debug-adapter',
    'gofumpt',
    'goimports',
    'hadolint',
    -- 'js-debug-adapter',
    'markdownlint',
    'markdown-toc',
    'prettier',
    'shellcheck',
    'shfmt',
    'stylua',
  },
  -- a handy list of special file types to be ignored by certain plugins (e.g. lualine)
  ignore_filetypes = {
    'OverseerList',
    'OverseerOutput',
    'blink-cmp-documentation',
    'blink-cmp-menu',
    'blink-cmp-signature',
    'checkhealth',
    'dap-repl',
    'dap-view',
    'dap-view-term',
    'gitsigns-blame',
    'lazy',
    'lazy_backdrop',
    'mason',
    'oil',
    'qf',
    'snacks_dashboard',
    'snacks_input',
    'snacks_layout_box',
    'snacks_notif',
    'snacks_notif_history',
    'snacks_picker_input',
    'snacks_picker_list',
    'snacks_picker_preview',
    'snacks_terminal',
    'snacks_win',
    'trouble',
  },
}
