return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cpp",
        "css",
        "dockerfile",
        "fish",
        "go",
        "gomod",
        "gosum",
        "groovy",
        "hcl",
        "helm",
        "html",
        "json",
        "json",
        "json5",
        "latex",
        "lua",
        "luadoc",
        "make",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "norg",
        "python",
        "regex",
        "ruby",
        "rust",
        "scss",
        "sql",
        "toml",
        "typescript",
        "vue",
        "xml",
        "yaml",
      },
    },
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      inlay_hints = { enabled = true },
    },
  },
}
