gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#a7c080'
      - bold
    inactiveBorderColor:
      - '#425047'
    optionsTextColor:
      - '#a7c080'
    selectedLineBgColor:
      - '#475258'
    selectedRangeBgColor:
      - '#475258'
    cherryPickedCommitBgColor:
      - '#4f585e'
    cherryPickedCommitFgColor:
      - '#a7c080'
    unstagedChangesColor:
      - '#e67e80'
    defaultFgColor:
      - '#d3c6aa'
    searchingActiveBorderColor:
      - '#dbbc7f'
